insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (1, 'Alpha', 101, '09:35', '11:10', 'Interstellar');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (2, 'Beta', 102, '12:15', '14:05', 'Shawshank Redemption');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (3, 'Theta', 103, '20:05', '21:50', 'The Vow');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (4, 'Gamma', 101, '16:15', '18:05', 'Shawshank Redemption');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (5, 'Beta', 103, '13:10', '15:00', 'Imitation Game');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (6, 'Alpha', 102, '11:35', '13:10', 'Interstellar');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (7, 'Alpha', 101, '10:05', '11:50', 'The Vow');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (8, 'Gamma', 103, '16:15', '18:30', 'Avatar');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (9, 'Theta', 102, '21:35', '23:10', 'Interstellar');
insert into show_entity ( show_id, show_name, theatre_id, start_time, end_time, movie_name) values (10, 'Beta', 101, '13:15', '15:30', 'Avatar');